### This is a draft.

name: Deploy Dev

on:
  registry_package:

jobs:
  set_env:
    uses: alexey-ban/ai-dial-ci/.github/workflows/gh_env.yml@review_env
    secrets: inherit
    with:
      environment_name: pr-${{ github.event.pull_request.number }}
      environment_url: "https://chat-ai-dial-themes-pr-${{ github.event.pull_request.number }}.gke.test.epam-rail.com"

      
  deploy_helm:
    uses: alexey-ban/ai-dial-ci/.github/workflows/k8s_env.yml@review_env
    if: ${{ github.event.registry_package.package_version.container_metadata.tag.name == 'development' }}
    needs:
      - set_env
    with:
      cloud_provider: "aws"
      k8s_namespace: dial # ???
      helm_values_file: "./build/helm/dev.yaml"
      helm_release_name: "ai-dial-chat-themes"
      helm_chart_name: "dial-extension"
      helm_chart_version: "1.0.6"
      helm_values: ""
      helm_extra_args: ""