name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - development
      # TODO: add release-* ??

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  plan:
    uses: nepalevov/ai-dial-ci/.github/workflows/gh_environment.yml@main
    with:
      operation: plan

  # TODO: replace with real build
  build:
    runs-on: ubuntu-latest
    needs:
      - plan
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          tags: |
            ${{ github.repository }}:${{ github.sha }}
            ${{ github.repository }}:${{ needs.plan.outputs.environment_name }}
          outputs: type=docker,dest=/tmp/image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: image
          path: /tmp/image.tar
