name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - development
      # TODO: add release-* ??

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  plan:
    uses: nepalevov/ai-dial-ci/.github/workflows/gh_environment.yml@main
    with:
      operation: plan

  # TODO: replace with real build
  build:
    needs:
      - plan
    uses: nepalevov/ai-dial-ci/actions/build_docker@main
    with:
      image_name: ${{ github.repository }}
      image_tag: ${{ github.sha }}
      image_extra_aliases: |
        ${{ github.repository }}:${{ needs.plan.outputs.environment_name }}
      outputs: type=docker,dest=/tmp/image.tar

  export:
    needs:
      - build
    uses: actions/upload-artifact@v4.4.3
    with:
      name: image
      path: /tmp/image.tar
