name: Create Environment

on:
  workflow_call:
    inputs:
      environment_name:
        type: string
        description: "The name of the environment to manage"
        required: true
      reviewers:
        type: string
        description: 'Comma-separated list of reviewers'
        required: false
        default: "20123880"

jobs:
  check-and-create-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          lfs: true

      - name: Update environment reviewers and policies
        env:
          ADMIN_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
          REVIEWERS: ${{ github.event.inputs.reviewers }}
        run: |
          # Convert the reviewers from a comma-separated string to a JSON array
          REVIEWERS_JSON=$(echo $REVIEWERS | jq -c 'split(",") | map({type: "User", id: .})')

          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${ADMIN_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/environments/${{ inputs.environment_name }} \
            -d @- <<EOF
          {
            "wait_timer": 0,
            "prevent_self_review": false,
            "reviewers": [{"type":"User","id":20123880}],
            "deployment_branch_policy": {
              "protected_branches": false,
              "custom_branch_policies": true
            }
          }
          EOF
