name: Manage Environments

on:
  workflow_call:
    inputs:
      environment_name:
        type: string
        description: "The name of the environment to manage"
        required: true
      reviewers:
        type: string
        description: 'Comma-separated list of reviewers'
        required: false
        default: "20123880"

jobs:
  check-and-create-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          lfs: true

      - name: Update environment reviewers and policies
        uses: octokit/request-action@dad4362715b7fb2ddedf9772c8670824af564f0d # v2.4        
        with:
          route: PUT /repos/${{ github.repository }}/environments/${{ github.event.inputs.environment_name }}
          data: |
            {
              "wait_timer": 0,
              "prevent_self_review": false,
              "reviewers": [{"type": "User", "id": 20123880}],
              "deployment_branch_policy": {
                "protected_branches": false,
                "custom_branch_policies": true
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
 