name: Manage Environments

on:
  workflow_call:
    inputs:
      environment_name:
        type: string
        description: "The name of the environment to manage"
        required: true
      reviewers:
        type: string
        description: 'Comma-separated list of reviewers'
        required: false
        default: "20123880"

jobs:
  check-and-create-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          lfs: true

      - name: Update environment reviewers and policies
        uses: actions/github-script@v6
        with:
          script: >
            const environmentName = '${{ github.event.inputs.environment_name }}';
            const reviewersInput = '${{ github.event.inputs.reviewers }}';
            const reviewers = reviewersInput ? reviewersInput.split(',').map(reviewer => ({ type: 'User', id: reviewer.trim() })) : [];
   
            await github.request('PUT /repos/{owner}/{repo}/environments/{environment_name}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: environmentName,
              headers: {
                'Accept': 'application/vnd.github+json',
                'Authorization': `Bearer ${process.env.ADMIN_TOKEN}`,
                'X-GitHub-Api-Version': '2022-11-28'
              },
              wait_timer: 0,
              prevent_self_review: false,
              reviewers: reviewers,
              deployment_branch_policy: {
                protected_branches: false,
                custom_branch_policies: true
              }
            });
        env:
          ADMIN_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
