name: Deploy Review

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches: 
      - development

jobs:
  create_env:
    uses: alexey-ban/ai-dial-ci/.github/workflows/gh_env.yml@review_env
    secrets:
      ACTIONS_BOT_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
    with:
      environment_create: true

  build_docker:
    uses: alexey-ban/ai-dial-ci/.github/workflows/generic_docker_review.yml@review_env
    secrets: inherit   
    needs:
      - create_env
    with:
      environment_name: ${{ needs.create_env.outputs.environment_name }}
      
  deploy_helm:
    uses: alexey-ban/ai-dial-ci/.github/workflows/k8s_env.yml@review_env
    needs:
      - create_env
      - build_docker
    with:
      cloud_provider: "gcp"
      k8s_namespace: ${{ github.repository_id }}-${{ needs.create_env.outputs.environment_name }}
      helm_values_file: "./build/helm/review.yaml"
      helm_values: "global.url=${{ needs.create_env.outputs.base_url }},themes.image.registry=${{ needs.build_docker.outputs.image_registry }},themes.image.repository=${{ needs.build_docker.outputs.image_repository }},themes.image.tag=${{ needs.build_docker.outputs.image_tag }}" # for epam we can delete themes.image.repository
      helm_extra_args: "--set-file core.extraConfig=./build/helm/review_core.json"

  run_e2e:
    uses: alexey-ban/ai-dial-ci/.github/workflows/run_e2e_test.yml@review_env
    needs:
      - create_env
      - deploy_helm
    with:
      url: ${{ needs.create_env.outputs.chat_url }}