name: Delete Environment

on:
  workflow_call:
    inputs:
      environment_name:
        type: string
        description: "The name of the environment to manage"
        required: true
      environment_destroy:
        type: boolean
        description: "Destroy environment"
        default: false

jobs:
  delete-environment:
    runs-on: ubuntu-latest

    steps:
      - name: "Cancel Workflow"
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # v0.12.1
        with:
          ignore_sha: true
          workflow_id: "all"

      - name: Sleep to debug
        run: |
            sleep 5

      - name: Delete Github environment
        if: ${{ inputs.environment_destroy}}
        uses: strumwolf/delete-deployment-environment@a4825dd9648c57da8437a4885c3fcad58beac69c # v3.0.0
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          environment: ${{ inputs.environment_name }}

      - name: Install kubectl
        uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f # v4.0.0
        with:
           version: 'v1.30.6'
      - name: Install helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: "v3.13.3"