### This is a draft.

name: E2E Test - Dev

on:
  registry_package:


jobs:    
  deploy_helm:
    uses: alexey-ban/ai-dial-ci/.github/workflows/k8s_env.yml@review_env
    if: ${{ github.event.registry_package.package_version.container_metadata.tag.name == 'development' }}
    with:
      cloud_provider: "gcp"
      k8s_namespace: ${{ github.repository_id }}-${{ github.sha }} # ToDO
      helm_values_file: "./build/helm/review.yaml"
      helm_values: "global.url=ai-dial-themes-${{ github.sha }}.gke.test.epam-rail.com"
      helm_extra_args: "--set-file core.extraConfig=./build/helm/review_core.json"

  run_e2e:
    uses: alexey-ban/ai-dial-ci/.github/workflows/run_e2e_test.yml@review_env
    if: ${{ github.event.registry_package.package_version.container_metadata.tag.name == 'development' }}
    needs:
      - deploy_helm
    with:
      url: "https://chat-ai-dial-themes-pr-${{ github.sha }}.gke.test.epam-rail.com"