name: Destroy Review

on:
  pull_request_target:
    types:
      - closed

jobs:
  delete-gh-environment:
    uses: nepalevov/ai-dial-ci/.github/workflows/gh_environment.yml@main
    with:
      operation: delete
    secrets:
      ACTIONS_BOT_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
    # HINT: outputs: ["environment_name", "environment_fqdn", "environment_url"]

  destroy:
    runs-on: ubuntu-latest
    needs:
      - delete-gh-environment
    steps:
      - run: |
          echo "Destroying the application in the cluster..."
          echo "Namespace: ${{ github.repository }}-${{ needs.delete-gh-environment.outputs.environment_name }}"
