# name: "Validate PR title"

# on:
#   pull_request_target:
#     types:
#       - opened
#       - edited
#       - synchronize

# jobs:
#   pr-title-check:
#     uses: alexey-ban/ai-dial-ci/.github/workflows/pr-title-check.yml@main
#     secrets:
#       ACTIONS_BOT_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
