name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

jobs:
  # run_tests:
  #   uses: alexey-ban/ai-dial-ci/.github/workflows/test.yml@main
  #   secrets: inherit 

    test:
      uses: ./.github/workflows/helm_deploy.yml
      with:
        k8s_namespace: ab-test
        helm_values_file: "./build/helm/review.yaml"