name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

jobs:
  # run_tests:
  #   uses: alexey-ban/ai-dial-ci/.github/workflows/test.yml@main
  #   secrets: inherit 

    test:
      uses: ./.github/workflows/helm_deploy.yml
      with:
        cloud_provider: "gcp"
        k8s_namespace: ${{ github.repository_id }}-pr-${{ github.event.pull_request.number }}
        helm_values_file: "./build/helm/review.yaml"
        helm_values: "global.url=ai-dial-themes-pr-${{ github.event.pull_request.number }}.gke.test.epam-rail.com"
        helm_extra_args: "--set-file core.extraConfig=./build/helm/review-core.json"